import { useState, useEffect } from 'react';
import { useParams, Link, useNavigate } from 'react-router-dom';
import { doc, getDoc, deleteDoc } from 'firebase/firestore';
import { db, auth } from '../firebase/config';
import { FaArrowLeft, FaDownload, FaPencilAlt, FaTrash } from 'react-icons/fa';
import { Alert, Button, Container, Modal } from '../components/ui';
import { cn } from '../utils/cn';
import { calculateDuration, formatDate, formatShortDate } from '../utils/dates';
import { formatINR } from '../utils/currency';
import { getDestinationImage } from '../utils/destinationImages';
import SafeImage from '../components/SafeImage';
import { viewDay, viewSlots } from '../utils/itinerary';
import { usePageTitle } from '../hooks/usePageTitle';

const TripDetails = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const [trip, setTrip] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [activeDay, setActiveDay] = useState(0);
  const [showDeleteModal, setShowDeleteModal] = useState(false);
  usePageTitle(trip?.destination ? trip.destination : 'Itinerary');

  useEffect(() => {
    const fetchTrip = async () => {
      try {
        const tripDoc = await getDoc(doc(db, 'trips', id));

        if (!tripDoc.exists()) {
          setError('Trip not found');
          setLoading(false);
          return;
        }

        const tripData = {
          id: tripDoc.id,
          ...tripDoc.data()
        };

        if (tripData.userId !== auth.currentUser?.uid) {
          setError('You do not have permission to view this trip');
          setLoading(false);
          return;
        }

        setTrip(tripData);
        setLoading(false);
      } catch (err) {
        console.error('Error fetching trip:', err);
        setError('Failed to load trip details. Please try again later.');
        setLoading(false);
      }
    };

    fetchTrip();
  }, [id]);

  const handleDeleteTrip = async () => {
    try {
      await deleteDoc(doc(db, 'trips', id));
      navigate('/dashboard');
    } catch (err) {
      console.error('Error deleting trip:', err);
      setError('Failed to delete trip. Please try again later.');
    }
  };

  const generateItineraryText = (currentTrip) => {
    let text = `TRAVEL ITINERARY: ${currentTrip.destination.toUpperCase()}\n`;
    text += `${formatDate(currentTrip.startDate)} to ${formatDate(currentTrip.endDate)}\n\n`;
    text += `TRIP SUMMARY:\n`;
    text += `Destination: ${currentTrip.destination}\n`;
    text += `Duration: ${calculateDuration(currentTrip.startDate, currentTrip.endDate)} days\n`;
    text += `Budget: ${formatINR(currentTrip.budget)}\n`;
    text += `Travelers: ${currentTrip.travelers}\n`;
    text += `Interests: ${currentTrip.interests.join(', ')}\n\n`;

    if (currentTrip.itinerary && currentTrip.itinerary.days) {
      text += `DAILY ITINERARY:\n\n`;
      currentTrip.itinerary.days.forEach((rawDay, index) => {
        const day = viewDay(rawDay, index);
        text += `DAY ${day.dayNumber}${day.title ? ` — ${day.title}` : ''}${day.date ? ` - ${day.date}` : ''}\n`;
        text += `------------------------\n`;
        viewSlots(rawDay).forEach((slot) => {
          text += `${slot.label.toUpperCase()}: ${slot.activity}\n`;
          text += `${slot.description}\n`;
          text += `Estimated Cost: ${formatINR(slot.estimatedCost)}\n\n`;
        });
        if (day.accommodation) {
          text += `ACCOMMODATION: ${day.accommodation.name}\n`;
          text += `${day.accommodation.description}\n`;
          text += `Estimated Cost: ${formatINR(day.accommodation.estimatedCost)}\n\n`;
        }
        text += `\n`;
      });
    }

    if (currentTrip.itinerary?.generalTips?.length) {
      text += `GENERAL TIPS:\n`;
      currentTrip.itinerary.generalTips.forEach((tip, index) => {
        text += `${index + 1}. ${tip}\n`;
      });
      text += `\n`;
    }

    text += `Total Estimated Cost: ${formatINR(currentTrip.itinerary?.totalEstimatedCost)}\n\n`;
    text += `Generated by Explore X — Your AI Travel Planner`;
    return text;
  };

  const downloadItinerary = () => {
    if (!trip) return;
    const itineraryText = generateItineraryText(trip);
    const blob = new Blob([itineraryText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${trip.destination.replace(/\s+/g, '-').toLowerCase()}-itinerary.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (loading) {
    return (
      <div className="flex min-h-[50vh] items-center justify-center" role="status">
        <p className="text-sm text-muted">Loading itinerary</p>
      </div>
    );
  }

  if (error) {
    return (
      <Container className="py-16">
        <Alert>{error}</Alert>
        <Link to="/dashboard" className="mt-4 inline-flex items-center gap-2 text-sm text-accent">
          <FaArrowLeft aria-hidden="true" /> Back to dashboard
        </Link>
      </Container>
    );
  }

  if (!trip || !trip.itinerary) {
    return (
      <Container className="py-16">
        <Alert tone="info">This trip doesn't have a generated itinerary yet or the data is incomplete.</Alert>
        <Link to="/dashboard" className="mt-4 inline-flex items-center gap-2 text-sm text-accent">
          <FaArrowLeft aria-hidden="true" /> Back to dashboard
        </Link>
      </Container>
    );
  }

  const image = getDestinationImage(trip.destination, trip.coverImage);
  const selectedDay = activeDay > 0 ? viewDay(trip.itinerary.days?.[activeDay - 1], activeDay - 1) : null;
  const slots = selectedDay ? viewSlots(trip.itinerary.days[activeDay - 1]) : [];

  return (
    <div>
      <section className="relative isolate min-h-[52vh] overflow-hidden">
        <SafeImage src={image} alt={trip.destination} priority className="absolute inset-0 h-full w-full object-cover" />
        <div className="absolute inset-0 bg-ink/55" />
        <Container className="relative flex min-h-[52vh] flex-col justify-end py-12 text-white">
          <Link to="/dashboard" className="mb-6 inline-flex items-center gap-2 text-sm text-white/80 hover:text-white">
            <FaArrowLeft aria-hidden="true" /> All trips
          </Link>
          <p className="text-xs uppercase tracking-[0.18em] text-white/70">Itinerary</p>
          <h1 className="mt-2 font-display text-5xl sm:text-6xl">{trip.destination}</h1>
          <p className="mt-3 text-white/85">
            {formatShortDate(trip.startDate)} – {formatShortDate(trip.endDate)} · {calculateDuration(trip.startDate, trip.endDate)} days
          </p>
        </Container>
      </section>

      <Container className="py-10 sm:py-14">
        <div className="flex flex-col gap-4 border-b border-line pb-8 sm:flex-row sm:items-center sm:justify-between">
          <div className="grid flex-1 gap-6 sm:grid-cols-3">
            <div>
              <p className="text-xs uppercase tracking-[0.14em] text-muted">Budget</p>
              <p className="mt-1 text-lg text-ink">{formatINR(trip.budget)}</p>
            </div>
            <div>
              <p className="text-xs uppercase tracking-[0.14em] text-muted">Travelers</p>
              <p className="mt-1 text-lg text-ink">{trip.travelers}</p>
            </div>
            <div>
              <p className="text-xs uppercase tracking-[0.14em] text-muted">Stay</p>
              <p className="mt-1 text-lg text-ink">{trip.accommodationType || 'Any'}</p>
            </div>
          </div>
          <div className="flex flex-wrap gap-2">
            <Button variant="secondary" size="sm" onClick={downloadItinerary}>
              <FaDownload aria-hidden="true" /> Download
            </Button>
            <Button variant="secondary" size="sm" to={`/trips/${id}/edit`}>
              <FaPencilAlt aria-hidden="true" /> Edit
            </Button>
            <Button variant="danger" size="sm" onClick={() => setShowDeleteModal(true)}>
              <FaTrash aria-hidden="true" /> Delete
            </Button>
          </div>
        </div>

        {trip.interests?.length > 0 && (
          <div className="mt-6 flex flex-wrap gap-2">
            {trip.interests.map((interest) => (
              <span key={interest} className="rounded-md bg-sand px-3 py-1 text-sm text-ink">
                {interest}
              </span>
            ))}
          </div>
        )}

        <div className="mt-10 flex gap-2 overflow-x-auto pb-2" role="tablist" aria-label="Itinerary days">
          <button
            type="button"
            role="tab"
            aria-selected={activeDay === 0}
            onClick={() => setActiveDay(0)}
            className={cn(
              'shrink-0 rounded-lg px-4 py-2 text-sm transition-colors focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-accent',
              activeDay === 0 ? 'bg-ink text-canvas' : 'bg-surface text-ink hover:bg-sand'
            )}
          >
            Overview
          </button>
          {trip.itinerary.days?.map((day, index) => (
            <button
              key={day.day || day.dayNumber || index}
              type="button"
              role="tab"
              aria-selected={activeDay === index + 1}
              onClick={() => setActiveDay(index + 1)}
              className={cn(
                'shrink-0 rounded-lg px-4 py-2 text-sm transition-colors focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-accent',
                activeDay === index + 1 ? 'bg-ink text-canvas' : 'bg-surface text-ink hover:bg-sand'
              )}
            >
              Day {day.day || day.dayNumber || index + 1}
            </button>
          ))}
        </div>

        {activeDay === 0 && (
          <div className="mt-10 grid gap-6 lg:grid-cols-2">
            {trip.itinerary.generalTips?.length > 0 && (
              <section className="rounded-xl border border-line bg-surface p-6 shadow-card">
                <h2 className="font-display text-2xl text-ink">Travel tips</h2>
                <ul className="mt-4 space-y-3 text-muted">
                  {trip.itinerary.generalTips.map((tip) => (
                    <li key={tip} className="border-b border-line pb-3 last:border-0 last:pb-0">
                      {tip}
                    </li>
                  ))}
                </ul>
              </section>
            )}
            {trip.itinerary.accommodationSuggestions?.length > 0 && (
              <section className="rounded-xl border border-line bg-surface p-6 shadow-card">
                <h2 className="font-display text-2xl text-ink">Accommodation</h2>
                <ul className="mt-4 space-y-3 text-muted">
                  {trip.itinerary.accommodationSuggestions.map((suggestion) => (
                    <li key={suggestion} className="border-b border-line pb-3 last:border-0 last:pb-0">
                      {suggestion}
                    </li>
                  ))}
                </ul>
              </section>
            )}
            {trip.itinerary.transportationOptions?.length > 0 && (
              <section className="rounded-xl border border-line bg-surface p-6 shadow-card">
                <h2 className="font-display text-2xl text-ink">Transportation</h2>
                <ul className="mt-4 space-y-3 text-muted">
                  {trip.itinerary.transportationOptions.map((option) => (
                    <li key={option} className="border-b border-line pb-3 last:border-0 last:pb-0">
                      {option}
                    </li>
                  ))}
                </ul>
              </section>
            )}
            <section className="rounded-xl border border-line bg-surface p-6 shadow-card">
              <h2 className="font-display text-2xl text-ink">Estimated total</h2>
              <p className="mt-4 font-display text-4xl text-accent">
                {formatINR(trip.itinerary.totalEstimatedCost)}
              </p>
              <p className="mt-3 text-sm text-muted">
                This is an estimate based on your preferences and may vary with bookings and season.
              </p>
            </section>
          </div>
        )}

        {selectedDay && (
          <article className="mt-10">
            <div className="mb-8 flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between">
              <div>
                <p className="text-xs uppercase tracking-[0.16em] text-accent">Day {selectedDay.dayNumber}</p>
                <h2 className="mt-1 font-display text-3xl text-ink">
                  {selectedDay.title || formatDate(selectedDay.date || trip.startDate)}
                </h2>
                {selectedDay.title ? (
                  <p className="mt-1 text-sm text-muted">{formatDate(selectedDay.date || trip.startDate)}</p>
                ) : null}
              </div>
              <p className="text-sm text-muted">Estimated day cost · {formatINR(selectedDay.estimatedCost)}</p>
            </div>

            <ol className="relative space-y-8 border-l border-line pl-6">
              {slots.map((slot, slotIndex) => (
                <li key={`${slot.label}-${slot.activity}-${slotIndex}`} className="relative">
                  <span className="absolute -left-[31px] top-1.5 h-2.5 w-2.5 rounded-full bg-accent" aria-hidden="true" />
                  <p className="text-xs uppercase tracking-[0.16em] text-muted">{slot.label}</p>
                  <h3 className="mt-1 text-xl font-medium text-ink">{slot.activity}</h3>
                  <p className="mt-2 leading-7 text-muted">{slot.description}</p>
                  <p className="mt-3 text-sm text-ink">Estimated cost · {formatINR(slot.estimatedCost)}</p>
                </li>
              ))}
              {selectedDay.accommodation && (
                <li className="relative">
                  <span className="absolute -left-[31px] top-1.5 h-2.5 w-2.5 rounded-full bg-ink" aria-hidden="true" />
                  <p className="text-xs uppercase tracking-[0.16em] text-muted">Accommodation</p>
                  <h3 className="mt-1 text-xl font-medium text-ink">{selectedDay.accommodation.name}</h3>
                  <p className="mt-2 leading-7 text-muted">{selectedDay.accommodation.description}</p>
                  <p className="mt-3 text-sm text-ink">Estimated cost · {formatINR(selectedDay.accommodation.estimatedCost)}</p>
                </li>
              )}
            </ol>
          </article>
        )}
      </Container>

      {showDeleteModal && (
        <Modal title="Delete this trip?" onClose={() => setShowDeleteModal(false)}>
          <p>This cannot be undone. The itinerary will be removed from your dashboard.</p>
          <div className="mt-6 flex justify-end gap-3">
            <Button variant="secondary" onClick={() => setShowDeleteModal(false)}>
              Cancel
            </Button>
            <Button variant="danger" onClick={handleDeleteTrip}>
              Delete
            </Button>
          </div>
        </Modal>
      )}
    </div>
  );
};

export default TripDetails;
